import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { MyThemeContextProvider } from "@/hooks/styleContext"; // Assuming this is the correct path to ThemeProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyThemeContextProvider>
          {/* Pass children to ThemeProvider */}
          {children}
        </MyThemeContextProvider>
      </body>
    </html>
  );
}
